# Generated by Django 5.2.6 on 2025-09-25 09:53

import myauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, blank=True, upload_to=myauth.models.avatar_image_directory_path),
        ),
    ]
